### ISSUE TITLE
[Suggestion] Support for internal images

### ISSUE THREAD

**Issue by Andre601** [StylexTV/GSigns#1]
From what I saw and understand does this plugin only support external images through a URL?
I would like if support for internal images could be added, similar to how BannerBoard has this option.

Like having an `img` folder, where you have your images and then reference the image itself in the code.

As an example:
Instead of having
```
{bg-url:https://raw.githubusercontent.com/StylexTV/GSigns/master/hypixel.png}
```
you would have an image called `hypixel.png` in the img-folder and reference it like this:
```
{bg-url:hypixel.png}
```

**Comment by stylextv** [comment]
I added this feature with the new update. Now you can use: e.g. {bg-img:picture.png} to load local images you dragged into the plugin folder. Thanks for the suggestion.
