### ISSUE TITLE
Loading item-frames

### ISSUE THREAD

**Issue by Nekiplay** [StylexTV/GSigns#11]
After rebooting to the server, or at a distance from the G-Sign, the Item-Frame will become empty, and you have to put the G-Sign back

**Comment by stylextv** [comment]
Hey, could you send me some more information?
I only test my plugins on fresh and newly installed spigot and paper spigot servers without any other plugins so issues that arouse out of the use of other plugin may happen.

**Comment by Nekiplay** [comment]
Server core Spigot 1.8.8

**Comment by stylextv** [comment]
Some more information? Like what plugins you use. Also does this only occure on your server or have you tried replicating this issue on a new and fresh 1.8.8 server?

**Comment by Nekiplay** [comment]
I use the following plugins
![image](https://user-images.githubusercontent.com/35975332/94317774-62766d00-ffa0-11ea-929e-05c8071e64a7.png)

**Comment by stylextv** [comment]
Thanks dude

**Comment by Nekiplay** [comment]
Image 3x3 blocks
![image](https://user-images.githubusercontent.com/35975332/94317945-d1ec5c80-ffa0-11ea-8e70-759c7a285707.png)
![image](https://user-images.githubusercontent.com/35975332/94318175-5939d000-ffa1-11ea-8e59-70a7432e9df2.png)
I checked when using: {bg-img:path} and {bg-url:link} they disappear

After restarting the server, the frames are empty
![image](https://user-images.githubusercontent.com/35975332/94318107-37d8e400-ffa1-11ea-89e4-7c573737e6c7.png)

**Comment by Nekiplay** [comment]
Also, when the player leaves the area of ​​drawing frames, they become ordinary empty frames that can be broken with a simple click.

**Comment by ProGitHubUser** [comment]
Can confirm this happens to me as well. 1.16.1 paper spigot
/save-all before restarting also doesn't fix this obviously

**Comment by stylextv** [comment]
Should be fixed in the latest version.
Let me know if it wasn't tho
