### ISSUE TITLE
Can't add Gif's from Files or URLs

### ISSUE THREAD

**Issue by corexti** [StylexTV/GSigns#2]
So I've tried adding few GIFs on the server but they won't work. I added the gifs to the images folder and one of those GIFs is the example mentioned in the description. Error message I get is STATUS_OPEN_ERROR. URL doesn't work either.

**Comment by stylextv** [comment]
The url value currently does not support gifs, but local gif files should load.
The loading of gifs isn't influenced by the server version, nor what other plugins you use, so I tested the gif on the spigot site again and it seems to work perfectly. Remember to put in the exact name of your file you placed into "GamemodeSigns/images". If you are unsure of how to use the create command do "/gs listfiles" and click on one of the files to get the command.

**Comment by corexti** [comment]
I was talking about gifs from local files too. It wouldn't open. Tried with the one gif in the wiki and all it gives is 'STATUS_OPEN_ERROR'. Any idea what could be the problem?

**Comment by stylextv** [comment]
Did you type /gs listfiles, clicked on the file and ran the command, or did you enter the command manually?

**Comment by corexti** [comment]
I used /gs listfiles, clicked on a gif, pressed enter and got the error.
With the latest update, I also can't use url's with .png extension.
`bg-url | Can't get input stream from URL!`
Command I use:
`/gs create {txt:Cookies,bg-url:https://raw.githubusercontent.com/StylexTV/GSigns/master/bg1.png}`

**Comment by corexti** [comment]
Just noticed today that it doesn't support https format of links for site url. When I change it to http, it works normally except it doesn't find the picture. When I change it to https I get Can't get input stream. Is the plugin incompatible with something? Or can this be from the plugin itself. Using latest 3.5 version.

**Comment by stylextv** [comment]
Yeah it could be from the plugin itself. The gif decoder I use is somewhat outdated. Maybe I'll rework it

**Comment by stylextv** [comment]
Added a new gif decoder
