### ISSUE TITLE
Fonts are not recognized correctly

### ISSUE THREAD

**Issue by AstragoDE** [StylexTV/GSigns#20]
For some reason I cannot change the font and font-size. This might be due to the Google Fonts update. 

Paper 1.16.4, 
GSigns: newest version

**Comment by stylextv** [comment]
This feature should still be working as the Google Fonts update should not have effects on my code. Could you explain what isn't working for you?

**Comment by AstragoDE** [comment]
I can only use the standard font, of which I can't change the font-size. 
Screenshot: http://cdn.astrago.de/Image.png

**Comment by stylextv** [comment]
Awesome shaders! 👍 
I'll look into it now.

**Comment by stylextv** [comment]
![2020-12-29_15 41 53](https://user-images.githubusercontent.com/56502218/103291585-64f7c100-49ec-11eb-83eb-aa1a5fb928c3.png)
It seems like everything is working for me. Maybe you misspelled a part of the command?
Here are the commands that I used to generate the images above:
/gs create {txt:"everything standard"}
/gs create {txt:"standard font; size: 180",fnt-siz:180}
/gs create {txt:"font: Pacifico-Regular; standard size",fnt:"Pacifico-Regular"}
/gs create {txt:"font: Pacifico-Regular; size: 180",fnt-siz:180,fnt:"Pacifico-Regular"}

**Comment by AstragoDE** [comment]
Hi, I tried out the commands you sent me, and changing the font size works indeed, but unfortunately I am unable to change the font.

PS: I use Sildurs Vibrant Shaders (https://sildurs-shaders.github.io/downloads/)

Edit: I accidentally added a space after the : in "fnt-siz**:**<some Number>".

http://cdn.astrago.de/Image2.png

**Comment by stylextv** [comment]
Ok, so even if you try out this command that I sent you earlier: `/gs create {txt:"font: Pacifico-Regular; standard size",fnt:"Pacifico-Regular"}`, it still renders the default font?

Edit: Oh I just noticed the screenshot you send me includes exactly these images. Do you see any errors in your console?

**Comment by AstragoDE** [comment]
I don't know if anything Changed, but everything is working now

**Comment by stylextv** [comment]
Looks to as if nothing has changed ;)
