### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by 00Hrtz** [StylexTV/GSigns#26]
Hi, I and another user posted in discussions 3 weeks ago and from the looks of it you're not reading them as theres a couple prior comments left un-replied too.

When is the plugin going to be updated to 1.17?

As is stands Gsigns is incompatible with 1.17+

https://paste.helpch.at/ukayexekoy.cs

Paper 1.17.1
MC 1.17.1

**Comment by SirCraftypants** [comment]
I'll explain a bit better, i have channels, some for single worlds, some worlds share a channel. these channels have their own image world prefixes and image rank prefixes hosted by itemsadder and luckperms.

I want players to auto join which ever channel the world has assigned to it when joining the world and leave the channel they were previous reading.writing in.
