### ISSUE TITLE
Doesnt work at all.

### ISSUE THREAD

**Issue by ablac** [StylexTV/GSigns#4]
Ive tested with 4 images and even Icons, and different size stone walls from 4x4 all the way up to 100 x 100 stone block walls, and no matter what when i left click the stone block i get "There Must be a solid blocks to hang a sign." Even on my Favicon for my website it wont even bring that in.

**Comment by stylextv** [comment]
Please look at the spigot site under "How to create a sign" to see how to correctly place signs:
https://www.spigotmc.org/resources/g-signs-a-unique-map-signs-plugin-for-lobbies.73693/

When creating a sign place the stone blocks where you want the item frames to be. The stone blocks will then be set to air and item frames will be summoned in that exact location, so make sure there are solid blocks (and also not stone blocks) behind the stone blocks.
