### ISSUE TITLE
Big problem with 1.12

### ISSUE THREAD

**Issue by SSKirillSS** [StylexTV/GSigns#5]
Hi. I'm using Mohist 1.12.2 and 4.0 version of this plugin.
So, my problem is pretty simple: any huge picture looks very bad.
Preview:
![image](https://user-images.githubusercontent.com/38190325/82612332-4b2b0b80-9bcb-11ea-9349-eb76cadfa457.png)
Command, that I use for testing: /gs create {bg-url:https://cdn.royalcanin-weshare-online.io/jyJEPmYBaxEApS7LtgZ4/v3/ec52h-older-cats-and-incontinence-causes-and-treatment-hero-cat}

Some notes:
If I use this pic on single stone block, it looks greater:
![image](https://user-images.githubusercontent.com/38190325/82612437-89282f80-9bcb-11ea-93de-3ee5efd4d909.png)
But if I place 3x2 stone blocks near of this one, it will be broken, as promoted on first screenshot.
![image](https://user-images.githubusercontent.com/38190325/82612532-bbd22800-9bcb-11ea-809d-e0a9f68d6477.png)
I also noticed that the frames are set 1 block higher than the stone. I don't know if this is normal.

UPD: Sorry 4 my Eng, I'm speak Rus.

**Comment by stylextv** [comment]
The frames shouldn't be set 1 block higher as the stone blocks and while trying out the command you provided I didn't encounter any problem. I will look into it tho

**Comment by SSKirillSS** [comment]
Maybe it caused by [mohist](https://mohist.red/).

**Comment by SSKirillSS** [comment]
Still an issue. Tested with G-Signs 4.1.
Demo: https://i.imgur.com/UKF7e6r.mp4

**Comment by stylextv** [comment]
I'm having issues with my pc lately therefore I'm not sure if I can fix this anytime soon. Getting interrupted by a hardware crash while working on a bug or new feature is devastating.

**Comment by stylextv** [comment]
Have you tried replicating this bug on a fresh, clean server?

**Comment by SSKirillSS** [comment]
> Have you tried replicating this bug on a fresh, clean server?

Updated mohist to 7bff7c2, G-Signs to 4.2, removed all other plugins, regenerated world.
Still an issue.
![image](https://user-images.githubusercontent.com/38190325/84504897-6c13e780-acc5-11ea-9db6-48d5d507aa2c.png)

Also, all pictures will update after creating a new one near it. So, I'll create a new at marked point, and now it looks like this:
![image](https://user-images.githubusercontent.com/38190325/84505160-e80e2f80-acc5-11ea-9b42-445a83a9211f.png)
More examples:
![image](https://user-images.githubusercontent.com/38190325/84505345-3d4a4100-acc6-11ea-97e4-ab36bc53662b.png)

**Comment by SSKirillSS** [comment]
Still an issue. Tested with 4.4

**Comment by stylextv** [comment]
I think I can close this now.
I didn't test the newest version with Mohist but I am fairly certain that it's fixed now since I redid a lot of the plugin's code.
We can reopen it at any time if it still persists tho.
