### ISSUE TITLE
1.16.2 error on startup

### ISSUE THREAD

**Issue by ghost** [StylexTV/GSigns#9]
the error plugin list and error from server log in the pastebin : https://pastebin.com/euUAM16B

**Comment by stylextv** [comment]
Thats a bug with paper spigot that I am already aware of.
I'll try to fix it but the plugin currently only supports the base spigot jars.

**Comment by stylextv** [comment]
Quick update: I fixed the bug myself (I also maybe commit the bug fix to ProtocolLib)
The fix will be included in the next update (4.9)
